In [1]:
import pandas as pd

In [2]:
def get_model(str_type):
    model = None
    decoding_version = None
    
    if str_type != "original":
        items = str_type.split('_')
        
        model = items[0]
        decoding_version = items[1]
    else:
        model = "human"
    return model

def get_decoding_version(str_type):
    model = None
    decoding_version = None
    
    if str_type != "original":
        items = str_type.split('_')
        
        model = items[0]
        decoding_version = items[1]
        
    else:
        decoding_version = "human"
        
    return decoding_version

In [3]:
df_joined_results = pd.read_csv('/home/pcallec/smoking_cessation_messages/results/vC/joined_output_vC_ChatGPT/joined_results.csv',
                              index_col = 0)

In [4]:
df_joined_results.head()

,Message,ID,model,type,index_prompt,message_position,selfBLEU4,app,underscore,less_than_six_words,prompt,decoding
0,“I can take just one puff” is a dangerous thou...,1.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,“The time is always right to do what is right”...,2.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,90% of those who quit smoking for 90 days are ...,3.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A slip is a sign that you need to improve your...,4.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A slip is not a full blown relapse. Make a com...,5.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get subset with all models but original

In [5]:
df_joined_results_shuffled = df_joined_results.sample(frac = 1, random_state=1234)
df_joined_results_shuffled.head(5)

,Message,ID,model,type,index_prompt,message_position,selfBLEU4,app,underscore,less_than_six_words,prompt,decoding
1487,You have the power to live your life without c...,NaN,gpt-j-6B,gpt-j-6B_prompt_v1_decoding_v1,91.0,4.0,0.054525,False,False,False,v1,v1
3148,It is important to recognize the benefits that...,NaN,opt-30b,opt-30b_prompt_v1_decoding_v1,48.0,3.0,0.168661,False,False,False,v1,v1
63,"Even if you have other health problems, such a...",65.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3596,Setting small achievable goals can help boost ...,NaN,ChatGPT,ChatGPT_prompt_v4,23.0,1.0,0.060282,False,False,False,v4,NaN
729,An irritable mood is expected during the early...,20361.0,original,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_joined_results_shuffled_2fields = df_joined_results_shuffled[["Message", "model"]]
df_joined_results_shuffled_2fields.head(5)

                                                Message     model
1487  You have the power to live your life without c...  gpt-j-6B
3148  It is important to recognize the benefits that...   opt-30b
63    Even if you have other health problems, such a...  original
3596  Setting small achievable goals can help boost ...   ChatGPT
729   An irritable mood is expected during the early...  original

In [7]:
df_joined_results_shuffled_2fields.sort_values(by=['model']).head()

                                                Message    model
3740  Keep track of your progress by writing down yo...  ChatGPT
3661  It's important to have a support system when q...  ChatGPT
3498  Replace smoking with a healthy habit, such as ...  ChatGPT
3474  When you feel a craving coming on, take a deep...  ChatGPT
3763  If you're trying to quit smoking, it's best to...  ChatGPT

In [8]:
l_models = df_joined_results_shuffled_2fields["model"].unique()
l_models

array(['gpt-j-6B', 'opt-30b', 'original', 'ChatGPT', 'opt-13b',
       'opt-6.7b', 'bloom-7b1'], dtype=object)

In [9]:
df_joined_results_shuffled_2fields.columns

Index(['Message', 'model'], dtype='object')

In [10]:
df_all = pd.DataFrame(columns = df_joined_results_shuffled_2fields.columns)
n_messages = 100

for model in l_models:
    df_temp = df_joined_results_shuffled_2fields[df_joined_results_shuffled_2fields["model"] == model]
    df_all = pd.concat([df_all, df_temp.iloc[:100,:]], ignore_index=True)

In [11]:
df_all.head()

                                             Message     model
0  You have the power to live your life without c...  gpt-j-6B
1  Your success isn’t determined by how much you ...  gpt-j-6B
2  To stop smoking completely, you need to go thr...  gpt-j-6B
3  What are your interests? What do you like to d...  gpt-j-6B
4  Talk to your friends, family, and colleagues a...  gpt-j-6B

In [12]:
df_all.tail()

                                               Message      model
695  Make a list of all the benefits of being a non...  bloom-7b1
696  If you are using a nicotine gum, you can stop ...  bloom-7b1
697  There are other ways to quit smoking, such as ...  bloom-7b1
698  Try to avoid stress, especially if you are try...  bloom-7b1
699  You are probably going to feel tired after qui...  bloom-7b1

In [13]:
df_all.to_csv("/home/pcallec/smoking_cessation_messages/results/vC/joined_output_vC_ChatGPT/joined_results_100.csv")