In [1]:
import pandas as pd

# vB: Prompt selection

## BLEU-4

We would use BLEU-4 with threshold 0.5

In [2]:
df_prompt_bleu4 = pd.read_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/self-BLEU-4/reduced/statistics_selfBLEU4.csv",
                              index_col = 0)

In [3]:
df_prompt_bleu4.head()

,filename,threshold,n_total,n_remaining,percentage_discarded
0,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,0.40,878,657,0.748292
1,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,0.45,878,670,0.763098
2,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,0.50,878,685,0.780182
3,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,0.55,878,708,0.806378
4,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,0.60,878,716,0.815490

In [4]:
df_prompt_bleu4["filename"].unique()

array(['prompt_input_v1_train_gen_gpt-j-6B_to_sentences_selfbleu4.csv',
       'prompt_input_v2_train_gen_gpt-j-6B_to_sentences_selfbleu4.csv',
       'prompt_input_v3_train_gen_gpt-j-6B_to_sentences_selfbleu4.csv',
       'prompt_input_v4_train_gen_gpt-j-6B_to_sentences_selfbleu4.csv',
       'prompt_input_v5_train_gen_gpt-j-6B_to_sentences_selfbleu4.csv',
       'prompt_input_v1_train_gen_bloom-7b1_to_sentences_selfbleu4.csv',
       'prompt_input_v2_train_gen_bloom-7b1_to_sentences_selfbleu4.csv',
       'prompt_input_v3_train_gen_bloom-7b1_to_sentences_selfbleu4.csv',
       'prompt_input_v4_train_gen_bloom-7b1_to_sentences_selfbleu4.csv',
       'prompt_input_v5_train_gen_bloom-7b1_to_sentences_selfbleu4.csv',
       'prompt_input_v1_train_gen_opt-6.7b_to_sentences_selfbleu4.csv',
       'prompt_input_v2_train_gen_opt-6.7b_to_sentences_selfbleu4.csv',
       'prompt_input_v3_train_gen_opt-6.7b_to_sentences_selfbleu4.csv',
       'prompt_input_v4_train_gen_opt-6.7b_to_sentences_selfbleu4.csv',
       'prompt_input_v5_train_gen_opt-6.7b_to_sentences_selfbleu4.csv',
       'prompt_input_v1_train_gen_opt-13b_to_sentences_selfbleu4.csv',
       'prompt_input_v2_train_gen_opt-13b_to_sentences_selfbleu4.csv',
       'prompt_input_v3_train_gen_opt-13b_to_sentences_selfbleu4.csv',
       'prompt_input_v4_train_gen_opt-13b_to_sentences_selfbleu4.csv',
       'prompt_input_v5_train_gen_opt-13b_to_sentences_selfbleu4.csv',
       'prompt_input_v1_train_gen_opt-30b_to_sentences_selfbleu4.csv',
       'prompt_input_v2_train_gen_opt-30b_to_sentences_selfbleu4.csv',
       'prompt_input_v3_train_gen_opt-30b_to_sentences_selfbleu4.csv',
       'prompt_input_v4_train_gen_opt-30b_to_sentences_selfbleu4.csv',
       'prompt_input_v5_train_gen_opt-30b_to_sentences_selfbleu4.csv'],
      dtype=object)

In [5]:
def get_prompt_version(str_type):

    items = str_type.split('_')
    
    prompt_version = items[2]
        
    return prompt_version

def get_model(str_type):
    items = str_type.split('_')
    
    model = items[5]
        
    return model

In [6]:
df_prompt_bleu4.insert(1, "model", df_prompt_bleu4["filename"].apply(get_model))
df_prompt_bleu4.insert(2, 'prompt_version', df_prompt_bleu4["filename"].apply(get_prompt_version))

In [7]:
df_prompt_bleu4.head()

,filename,model,prompt_version,threshold,n_total,n_remaining,percentage_discarded
0,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,0.40,878,657,0.748292
1,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,0.45,878,670,0.763098
2,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,0.50,878,685,0.780182
3,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,0.55,878,708,0.806378
4,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,0.60,878,716,0.815490

In [8]:
df_prompt_bleu4 = df_prompt_bleu4.drop(columns=["filename"])
df_prompt_bleu4.head()

,model,prompt_version,threshold,n_total,n_remaining,percentage_discarded
0,gpt-j-6B,v1,0.40,878,657,0.748292
1,gpt-j-6B,v1,0.45,878,670,0.763098
2,gpt-j-6B,v1,0.50,878,685,0.780182
3,gpt-j-6B,v1,0.55,878,708,0.806378
4,gpt-j-6B,v1,0.60,878,716,0.815490

In [9]:
df_prompt_bleu4_th05 = df_prompt_bleu4.query("threshold == 0.50")
df_prompt_bleu4_th05 = df_prompt_bleu4_th05.drop(columns=["threshold"])

In [10]:
df_prompt_bleu4_th05.head()

       model prompt_version  n_total  n_remaining  percentage_discarded
2   gpt-j-6B             v1      878          685              0.780182
7   gpt-j-6B             v2      925          675              0.729730
12  gpt-j-6B             v3      930          712              0.765591
17  gpt-j-6B             v4     1523          402              0.263953
22  gpt-j-6B             v5      772          562              0.727979

In [11]:
dict_new_names = {"n_remaining":"BLEU4_remaining", "percentage_discarded":r"BLEU4_%remaining"}
df_prompt_bleu4_th05 = df_prompt_bleu4_th05.rename(columns=dict_new_names)

In [12]:
df_prompt_bleu4_th05.head()

       model prompt_version  n_total  BLEU4_remaining  BLEU4_%remaining
2   gpt-j-6B             v1      878              685          0.780182
7   gpt-j-6B             v2      925              675          0.729730
12  gpt-j-6B             v3      930              712          0.765591
17  gpt-j-6B             v4     1523              402          0.263953
22  gpt-j-6B             v5      772              562          0.727979

In [13]:
df_prompt_bleu4_th05[r"BLEU4_%discarded"] = 1 - df_prompt_bleu4_th05[r"BLEU4_%remaining"]

In [14]:
df_prompt_bleu4_th05.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
2,gpt-j-6B,v1,878,685,0.780182,0.219818
7,gpt-j-6B,v2,925,675,0.729730,0.270270
12,gpt-j-6B,v3,930,712,0.765591,0.234409
17,gpt-j-6B,v4,1523,402,0.263953,0.736047
22,gpt-j-6B,v5,772,562,0.727979,0.272021

In [15]:
df_prompt_bleu4_th05["model"] = df_prompt_bleu4_th05["model"].apply(str.upper)

In [16]:
df_prompt_bleu4_th05.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
2,GPT-J-6B,v1,878,685,0.780182,0.219818
7,GPT-J-6B,v2,925,675,0.729730,0.270270
12,GPT-J-6B,v3,930,712,0.765591,0.234409
17,GPT-J-6B,v4,1523,402,0.263953,0.736047
22,GPT-J-6B,v5,772,562,0.727979,0.272021

In [17]:
df_prompt_bleu4_th05.insert(0, "model_prompt_version", df_prompt_bleu4_th05['model'] +"_"+ df_prompt_bleu4_th05["prompt_version"])

In [18]:
df_prompt_bleu4_th05.head()

,model_prompt_version,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
2,GPT-J-6B_v1,GPT-J-6B,v1,878,685,0.780182,0.219818
7,GPT-J-6B_v2,GPT-J-6B,v2,925,675,0.729730,0.270270
12,GPT-J-6B_v3,GPT-J-6B,v3,930,712,0.765591,0.234409
17,GPT-J-6B_v4,GPT-J-6B,v4,1523,402,0.263953,0.736047
22,GPT-J-6B_v5,GPT-J-6B,v5,772,562,0.727979,0.272021

In [19]:
df_prompt_bleu4_th05.dtypes

model_prompt_version     object
model                    object
prompt_version           object
n_total                   int64
BLEU4_remaining           int64
BLEU4_%remaining        float64
BLEU4_%discarded        float64
dtype: object

## Read criteria

In [20]:
df_prompt_criteria = pd.read_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/criteria/statistics_discard.csv",
                                 index_col = 0)

In [21]:
df_prompt_criteria.head()

,filename,n_total,n_app,n_underscore,n_less_than_six_words,n_remaining,percentage
0,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,685,0,0,42,643,0.938686
1,prompt_input_v2_train_gen_gpt-j-6B_to_sentence...,675,0,0,33,642,0.951111
2,prompt_input_v3_train_gen_gpt-j-6B_to_sentence...,712,0,0,31,681,0.956461
3,prompt_input_v4_train_gen_gpt-j-6B_to_sentence...,402,0,29,138,263,0.654229
4,prompt_input_v5_train_gen_gpt-j-6B_to_sentence...,562,2,0,31,529,0.941281

In [22]:
df_prompt_criteria.insert(1, "model", df_prompt_criteria["filename"].apply(get_model))
df_prompt_criteria.insert(2, 'prompt_version', df_prompt_criteria["filename"].apply(get_prompt_version))

In [23]:
df_prompt_criteria.head()

,filename,model,prompt_version,n_total,n_app,n_underscore,n_less_than_six_words,n_remaining,percentage
0,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,685,0,0,42,643,0.938686
1,prompt_input_v2_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v2,675,0,0,33,642,0.951111
2,prompt_input_v3_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v3,712,0,0,31,681,0.956461
3,prompt_input_v4_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v4,402,0,29,138,263,0.654229
4,prompt_input_v5_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v5,562,2,0,31,529,0.941281

In [24]:
dict_new_names = {"n_app":"Criteria_n_app", "n_underscore":"Criteria_n_underscore",
                  "n_less_than_six_words": "Criteria_n_less_than_six_words",
                  "n_remaining": "Criteria_n_remaining",
                  "percentage": r"Criteria_%remaining2"}
df_prompt_criteria = df_prompt_criteria.rename(columns=dict_new_names)

In [25]:
df_prompt_criteria.head()

,filename,model,prompt_version,n_total,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,prompt_input_v1_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v1,685,0,0,42,643,0.938686
1,prompt_input_v2_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v2,675,0,0,33,642,0.951111
2,prompt_input_v3_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v3,712,0,0,31,681,0.956461
3,prompt_input_v4_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v4,402,0,29,138,263,0.654229
4,prompt_input_v5_train_gen_gpt-j-6B_to_sentence...,gpt-j-6B,v5,562,2,0,31,529,0.941281

In [26]:
df_prompt_criteria = df_prompt_criteria.drop(columns=["filename","n_total"])
df_prompt_criteria["model"] = df_prompt_criteria["model"].apply(str.upper)

In [27]:
df_prompt_criteria.head()

,model,prompt_version,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,0,0,42,643,0.938686
1,GPT-J-6B,v2,0,0,33,642,0.951111
2,GPT-J-6B,v3,0,0,31,681,0.956461
3,GPT-J-6B,v4,0,29,138,263,0.654229
4,GPT-J-6B,v5,2,0,31,529,0.941281

In [28]:
df_prompt_criteria.insert(0, "model_prompt_version",
                          df_prompt_criteria['model'] +"_"+ df_prompt_criteria["prompt_version"])

In [29]:
df_prompt_criteria.head()

,model_prompt_version,model,prompt_version,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B_v1,GPT-J-6B,v1,0,0,42,643,0.938686
1,GPT-J-6B_v2,GPT-J-6B,v2,0,0,33,642,0.951111
2,GPT-J-6B_v3,GPT-J-6B,v3,0,0,31,681,0.956461
3,GPT-J-6B_v4,GPT-J-6B,v4,0,29,138,263,0.654229
4,GPT-J-6B_v5,GPT-J-6B,v5,2,0,31,529,0.941281

In [30]:
df_prompt_bleu4_th05.dtypes

model_prompt_version     object
model                    object
prompt_version           object
n_total                   int64
BLEU4_remaining           int64
BLEU4_%remaining        float64
BLEU4_%discarded        float64
dtype: object

In [31]:
df_prompt_criteria.dtypes

model_prompt_version               object
model                              object
prompt_version                     object
Criteria_n_app                      int64
Criteria_n_underscore               int64
Criteria_n_less_than_six_words      int64
Criteria_n_remaining                int64
Criteria_%remaining2              float64
dtype: object

In [32]:
# https://stackoverflow.com/questions/50649853/trying-to-merge-2-dataframes-but-get-valueerror
# It gives error because it's using index of bleu df

df_prompt_joined = df_prompt_bleu4_th05.merge(df_prompt_criteria, on = "model_prompt_version",
                           suffixes = (None, "_y"))
df_prompt_joined.head()

,model_prompt_version,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,model_y,prompt_version_y,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B_v1,GPT-J-6B,v1,878,685,0.780182,0.219818,GPT-J-6B,v1,0,0,42,643,0.938686
1,GPT-J-6B_v2,GPT-J-6B,v2,925,675,0.729730,0.270270,GPT-J-6B,v2,0,0,33,642,0.951111
2,GPT-J-6B_v3,GPT-J-6B,v3,930,712,0.765591,0.234409,GPT-J-6B,v3,0,0,31,681,0.956461
3,GPT-J-6B_v4,GPT-J-6B,v4,1523,402,0.263953,0.736047,GPT-J-6B,v4,0,29,138,263,0.654229
4,GPT-J-6B_v5,GPT-J-6B,v5,772,562,0.727979,0.272021,GPT-J-6B,v5,2,0,31,529,0.941281

In [33]:
df_prompt_joined = df_prompt_joined.drop(columns = ["model_prompt_version", "model_y" , "prompt_version_y"])
df_prompt_joined.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,878,685,0.780182,0.219818,0,0,42,643,0.938686
1,GPT-J-6B,v2,925,675,0.729730,0.270270,0,0,33,642,0.951111
2,GPT-J-6B,v3,930,712,0.765591,0.234409,0,0,31,681,0.956461
3,GPT-J-6B,v4,1523,402,0.263953,0.736047,0,29,138,263,0.654229
4,GPT-J-6B,v5,772,562,0.727979,0.272021,2,0,31,529,0.941281

In [34]:
df_prompt_joined.insert(9, "Criteria_n_discarded", df_prompt_joined["BLEU4_remaining"] - df_prompt_joined["Criteria_n_remaining"])

In [35]:
df_prompt_joined.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,878,685,0.780182,0.219818,0,0,42,42,643,0.938686
1,GPT-J-6B,v2,925,675,0.729730,0.270270,0,0,33,33,642,0.951111
2,GPT-J-6B,v3,930,712,0.765591,0.234409,0,0,31,31,681,0.956461
3,GPT-J-6B,v4,1523,402,0.263953,0.736047,0,29,138,139,263,0.654229
4,GPT-J-6B,v5,772,562,0.727979,0.272021,2,0,31,33,529,0.941281

In [36]:
df_prompt_joined.insert(12, r"Criteria_%discarded", df_prompt_joined["Criteria_n_discarded"]/df_prompt_joined["n_total"])

In [37]:
df_prompt_joined.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining2,Criteria_%discarded
0,GPT-J-6B,v1,878,685,0.780182,0.219818,0,0,42,42,643,0.938686,0.047836
1,GPT-J-6B,v2,925,675,0.729730,0.270270,0,0,33,33,642,0.951111,0.035676
2,GPT-J-6B,v3,930,712,0.765591,0.234409,0,0,31,31,681,0.956461,0.033333
3,GPT-J-6B,v4,1523,402,0.263953,0.736047,0,29,138,139,263,0.654229,0.091267
4,GPT-J-6B,v5,772,562,0.727979,0.272021,2,0,31,33,529,0.941281,0.042746

In [38]:
df_prompt_joined.insert(11, r"Criteria_%remaining", df_prompt_joined["Criteria_n_remaining"]/df_prompt_joined["n_total"])

In [39]:
df_prompt_joined.head()

,model,prompt_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
0,GPT-J-6B,v1,878,685,0.780182,0.219818,0,0,42,42,643,0.732346,0.938686,0.047836
1,GPT-J-6B,v2,925,675,0.729730,0.270270,0,0,33,33,642,0.694054,0.951111,0.035676
2,GPT-J-6B,v3,930,712,0.765591,0.234409,0,0,31,31,681,0.732258,0.956461,0.033333
3,GPT-J-6B,v4,1523,402,0.263953,0.736047,0,29,138,139,263,0.172685,0.654229,0.091267
4,GPT-J-6B,v5,772,562,0.727979,0.272021,2,0,31,33,529,0.685233,0.941281,0.042746

In [40]:
df_prompt_joined_mean = df_prompt_joined.groupby(["prompt_version"]).mean()
df_prompt_joined_mean

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
prompt_version,,,,,,,,,,,,
v1,739.2,545.0,0.729648,0.270352,0.8,0.0,29.8,30.6,514.4,0.691205,0.947856,0.038443
v2,754.2,576.8,0.765224,0.234776,1.8,0.0,24.8,26.4,550.4,0.732676,0.956446,0.032549
v3,803.4,598.0,0.749408,0.250592,0.8,0.0,26.8,27.6,570.4,0.717349,0.956182,0.032059
v4,1376.0,365.6,0.272490,0.727510,1.2,6.4,100.8,102.8,262.8,0.202389,0.733128,0.070101
v5,673.0,454.2,0.670465,0.329535,0.8,0.0,21.6,22.4,431.8,0.638460,0.953573,0.032006

In [41]:
df_prompt_joined.groupby(["prompt_version"]).count()

,model,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
prompt_version,,,,,,,,,,,,,
v1,5,5,5,5,5,5,5,5,5,5,5,5,5
v2,5,5,5,5,5,5,5,5,5,5,5,5,5
v3,5,5,5,5,5,5,5,5,5,5,5,5,5
v4,5,5,5,5,5,5,5,5,5,5,5,5,5
v5,5,5,5,5,5,5,5,5,5,5,5,5,5

In [42]:
df_prompt_joined_mean.to_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/stats_filters/prompt_filters_joined_mean.csv")

In [43]:
df_prompt_joined.groupby(["prompt_version"]).count()["model"]

prompt_version
v1    5
v2    5
v3    5
v4    5
v5    5
Name: model, dtype: int64

In [44]:
df_prompt_joined_stddev = df_prompt_joined.groupby(["prompt_version"]).std()
df_prompt_joined_stddev

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
prompt_version,,,,,,,,,,,,
v1,165.341162,147.778551,0.054328,0.054328,0.836660,0.000000,16.452963,16.164777,133.932072,0.048274,0.024473,0.017953
v2,197.227534,152.470325,0.057760,0.057760,2.167948,0.000000,18.700267,17.285832,143.780388,0.070850,0.026553,0.018980
v3,207.571193,155.183762,0.076647,0.076647,1.303840,0.000000,13.179530,13.221195,144.937228,0.082454,0.019314,0.012463
v4,353.307232,70.251690,0.036585,0.036585,1.095445,12.660964,45.920584,46.354072,29.003448,0.056756,0.101948,0.023812
v5,86.717934,86.082519,0.046362,0.046362,0.836660,0.000000,15.290520,15.485477,75.945375,0.032703,0.032454,0.022639

In [45]:
df_prompt_joined_stddev.to_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/stats_filters/prompt_filters_joined_stddev.csv")

In [46]:
df_prompt_joined_stderr = df_prompt_joined.groupby(["prompt_version"]).std()/5**0.5
df_prompt_joined_stderr

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
prompt_version,,,,,,,,,,,,
v1,73.942816,66.088577,0.024296,0.024296,0.374166,0.000000,7.357989,7.229108,59.896244,0.021589,0.010944,0.008029
v2,88.202834,68.186802,0.025831,0.025831,0.969536,0.000000,8.363014,7.730459,64.300544,0.031685,0.011875,0.008488
v3,92.828659,69.400288,0.034277,0.034277,0.583095,0.000000,5.894065,5.912698,64.817899,0.036875,0.008638,0.005574
v4,158.003797,31.417511,0.016361,0.016361,0.489898,5.662155,20.536309,20.730171,12.970736,0.025382,0.045593,0.010649
v5,38.781439,38.497273,0.020734,0.020734,0.374166,0.000000,6.838128,6.925316,33.963804,0.014625,0.014514,0.010124

In [47]:
df_prompt_joined_stderr.to_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/stats_filters/prompt_filters_joined_stderr.csv")

# VC: decoding strategy selection

## BLEU-4

In [48]:
df_decoding_bleu4 = pd.read_csv("/home/pcallec/smoking_cessation_messages/results/vC/self-BLEU-4/reduced/statistics_selfBLEU4.csv", index_col = 0)

In [49]:
df_decoding_bleu4.head()

,filename,threshold,n_total,n_remaining,percentage_discarded
0,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,0.4,867,630,0.726644
1,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,0.5,867,659,0.760092
2,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,0.4,439,422,0.961276
3,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,0.5,439,424,0.965831
4,prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...,0.4,349,339,0.971347

In [50]:
df_decoding_bleu4["filename"].head()

0    prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...
1    prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...
2    prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...
3    prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...
4    prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...
Name: filename, dtype: object

In [51]:
df_decoding_bleu4["filename"][0]

'prompt_input_v1_train_gen_gpt-j-6B_decoding_v1_to_sentences_selfbleu4.csv'

In [52]:
def get_decoding_version(str_type):
    model = None
    decoding_version = None
    
    if str_type != "original":
        items = str_type.split('_')
        
        model = items[0]
        decoding_version = items[7]
        
    else:
        decoding_version = "human"
        
    return decoding_version

def get_model(str_type):
    items = str_type.split('_')
    
    model = items[5]
        
    return model

In [53]:
df_decoding_bleu4["filename"].apply(get_decoding_version)

0     v1
1     v1
2     v2
3     v2
4     v3
      ..
75    v6
76    v7
77    v7
78    v8
79    v8
Name: filename, Length: 80, dtype: object

In [54]:
df_decoding_bleu4.insert(1, "model", df_decoding_bleu4["filename"].apply(get_model))
df_decoding_bleu4.insert(2, 'decoding_version', df_decoding_bleu4["filename"].apply(get_decoding_version))

In [55]:
df_decoding_bleu4.head()

,filename,model,decoding_version,threshold,n_total,n_remaining,percentage_discarded
0,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,gpt-j-6B,v1,0.4,867,630,0.726644
1,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,gpt-j-6B,v1,0.5,867,659,0.760092
2,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,gpt-j-6B,v2,0.4,439,422,0.961276
3,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,gpt-j-6B,v2,0.5,439,424,0.965831
4,prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...,gpt-j-6B,v3,0.4,349,339,0.971347

In [56]:
df_decoding_bleu4 = df_decoding_bleu4.drop(columns=["filename"])
df_decoding_bleu4.head()

,model,decoding_version,threshold,n_total,n_remaining,percentage_discarded
0,gpt-j-6B,v1,0.4,867,630,0.726644
1,gpt-j-6B,v1,0.5,867,659,0.760092
2,gpt-j-6B,v2,0.4,439,422,0.961276
3,gpt-j-6B,v2,0.5,439,424,0.965831
4,gpt-j-6B,v3,0.4,349,339,0.971347

In [57]:
df_decoding_bleu4_th05 = df_decoding_bleu4.query("threshold == 0.50")
df_decoding_bleu4_th05 = df_decoding_bleu4_th05.drop(columns=["threshold"])

In [58]:
df_decoding_bleu4_th05.head()

      model decoding_version  n_total  n_remaining  percentage_discarded
1  gpt-j-6B               v1      867          659              0.760092
3  gpt-j-6B               v2      439          424              0.965831
5  gpt-j-6B               v3      349          339              0.971347
7  gpt-j-6B               v4      469          462              0.985075
9  gpt-j-6B               v5      781          600              0.768246

In [59]:
dict_new_names = {"n_remaining":"BLEU4_remaining", "percentage_discarded":r"BLEU4_%remaining"}
df_decoding_bleu4_th05 = df_decoding_bleu4_th05.rename(columns=dict_new_names)

In [60]:
df_decoding_bleu4_th05.head()

      model decoding_version  n_total  BLEU4_remaining  BLEU4_%remaining
1  gpt-j-6B               v1      867              659          0.760092
3  gpt-j-6B               v2      439              424          0.965831
5  gpt-j-6B               v3      349              339          0.971347
7  gpt-j-6B               v4      469              462          0.985075
9  gpt-j-6B               v5      781              600          0.768246

In [61]:
df_decoding_bleu4_th05[r"BLEU4_%discarded"] = 1 - df_decoding_bleu4_th05[r"BLEU4_%remaining"]

In [62]:
df_decoding_bleu4_th05.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
1,gpt-j-6B,v1,867,659,0.760092,0.239908
3,gpt-j-6B,v2,439,424,0.965831,0.034169
5,gpt-j-6B,v3,349,339,0.971347,0.028653
7,gpt-j-6B,v4,469,462,0.985075,0.014925
9,gpt-j-6B,v5,781,600,0.768246,0.231754

In [63]:
df_decoding_bleu4_th05["model"] = df_decoding_bleu4_th05["model"].apply(str.upper)

In [64]:
df_decoding_bleu4_th05.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
1,GPT-J-6B,v1,867,659,0.760092,0.239908
3,GPT-J-6B,v2,439,424,0.965831,0.034169
5,GPT-J-6B,v3,349,339,0.971347,0.028653
7,GPT-J-6B,v4,469,462,0.985075,0.014925
9,GPT-J-6B,v5,781,600,0.768246,0.231754

In [65]:
df_decoding_bleu4_th05.insert(0, "model_decoding_version", df_decoding_bleu4_th05['model'] +"_"+ df_decoding_bleu4_th05["decoding_version"])

In [66]:
df_decoding_bleu4_th05.head()

,model_decoding_version,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
1,GPT-J-6B_v1,GPT-J-6B,v1,867,659,0.760092,0.239908
3,GPT-J-6B_v2,GPT-J-6B,v2,439,424,0.965831,0.034169
5,GPT-J-6B_v3,GPT-J-6B,v3,349,339,0.971347,0.028653
7,GPT-J-6B_v4,GPT-J-6B,v4,469,462,0.985075,0.014925
9,GPT-J-6B_v5,GPT-J-6B,v5,781,600,0.768246,0.231754

In [67]:
df_decoding_bleu4_th05.dtypes

model_decoding_version     object
model                      object
decoding_version           object
n_total                     int64
BLEU4_remaining             int64
BLEU4_%remaining          float64
BLEU4_%discarded          float64
dtype: object

## Read criteria

In [68]:
df_decoding_criteria = pd.read_csv("/home/pcallec/smoking_cessation_messages/results/vC/criteria/statistics_discard.csv",
                                   index_col = 0)

In [69]:
df_decoding_criteria.head()

,filename,n_total,n_app,n_underscore,n_less_than_six_words,n_remaining,percentage
0,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,659,1,0,29,629,0.954476
1,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,424,2,1,4,417,0.983491
2,prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...,339,1,0,16,322,0.949853
3,prompt_input_v1_train_gen_gpt-j-6B_decoding_v4...,462,2,0,7,453,0.980519
4,prompt_input_v1_train_gen_gpt-j-6B_decoding_v5...,600,1,0,35,564,0.940000

In [70]:
df_decoding_criteria.insert(1, "model", df_decoding_criteria["filename"].apply(get_model))
df_decoding_criteria.insert(2, 'decoding_version', df_decoding_criteria["filename"].apply(get_decoding_version))

In [71]:
df_decoding_criteria.head()

,filename,model,decoding_version,n_total,n_app,n_underscore,n_less_than_six_words,n_remaining,percentage
0,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,gpt-j-6B,v1,659,1,0,29,629,0.954476
1,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,gpt-j-6B,v2,424,2,1,4,417,0.983491
2,prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...,gpt-j-6B,v3,339,1,0,16,322,0.949853
3,prompt_input_v1_train_gen_gpt-j-6B_decoding_v4...,gpt-j-6B,v4,462,2,0,7,453,0.980519
4,prompt_input_v1_train_gen_gpt-j-6B_decoding_v5...,gpt-j-6B,v5,600,1,0,35,564,0.940000

In [72]:
dict_new_names = {"n_app":"Criteria_n_app", "n_underscore":"Criteria_n_underscore",
                  "n_less_than_six_words": "Criteria_n_less_than_six_words",
                  "n_remaining": "Criteria_n_remaining",
                  "percentage": r"Criteria_%remaining2"}
df_decoding_criteria = df_decoding_criteria.rename(columns=dict_new_names)

In [73]:
df_decoding_criteria.head()

,filename,model,decoding_version,n_total,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,prompt_input_v1_train_gen_gpt-j-6B_decoding_v1...,gpt-j-6B,v1,659,1,0,29,629,0.954476
1,prompt_input_v1_train_gen_gpt-j-6B_decoding_v2...,gpt-j-6B,v2,424,2,1,4,417,0.983491
2,prompt_input_v1_train_gen_gpt-j-6B_decoding_v3...,gpt-j-6B,v3,339,1,0,16,322,0.949853
3,prompt_input_v1_train_gen_gpt-j-6B_decoding_v4...,gpt-j-6B,v4,462,2,0,7,453,0.980519
4,prompt_input_v1_train_gen_gpt-j-6B_decoding_v5...,gpt-j-6B,v5,600,1,0,35,564,0.940000

In [74]:
df_decoding_criteria = df_decoding_criteria.drop(columns=["filename","n_total"])
df_decoding_criteria["model"] = df_decoding_criteria["model"].apply(str.upper)

In [75]:
df_decoding_criteria.head()

,model,decoding_version,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,1,0,29,629,0.954476
1,GPT-J-6B,v2,2,1,4,417,0.983491
2,GPT-J-6B,v3,1,0,16,322,0.949853
3,GPT-J-6B,v4,2,0,7,453,0.980519
4,GPT-J-6B,v5,1,0,35,564,0.940000

In [76]:
df_decoding_criteria.insert(0, "model_decoding_version", df_decoding_criteria['model'] +"_"+ df_decoding_criteria["decoding_version"])

In [77]:
df_decoding_criteria.head()

,model_decoding_version,model,decoding_version,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B_v1,GPT-J-6B,v1,1,0,29,629,0.954476
1,GPT-J-6B_v2,GPT-J-6B,v2,2,1,4,417,0.983491
2,GPT-J-6B_v3,GPT-J-6B,v3,1,0,16,322,0.949853
3,GPT-J-6B_v4,GPT-J-6B,v4,2,0,7,453,0.980519
4,GPT-J-6B_v5,GPT-J-6B,v5,1,0,35,564,0.940000

In [78]:
df_decoding_criteria.dtypes

model_decoding_version             object
model                              object
decoding_version                   object
Criteria_n_app                      int64
Criteria_n_underscore               int64
Criteria_n_less_than_six_words      int64
Criteria_n_remaining                int64
Criteria_%remaining2              float64
dtype: object

In [79]:
df_decoding_criteria.head()

,model_decoding_version,model,decoding_version,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B_v1,GPT-J-6B,v1,1,0,29,629,0.954476
1,GPT-J-6B_v2,GPT-J-6B,v2,2,1,4,417,0.983491
2,GPT-J-6B_v3,GPT-J-6B,v3,1,0,16,322,0.949853
3,GPT-J-6B_v4,GPT-J-6B,v4,2,0,7,453,0.980519
4,GPT-J-6B_v5,GPT-J-6B,v5,1,0,35,564,0.940000

In [80]:
df_decoding_bleu4_th05.head()

,model_decoding_version,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded
1,GPT-J-6B_v1,GPT-J-6B,v1,867,659,0.760092,0.239908
3,GPT-J-6B_v2,GPT-J-6B,v2,439,424,0.965831,0.034169
5,GPT-J-6B_v3,GPT-J-6B,v3,349,339,0.971347,0.028653
7,GPT-J-6B_v4,GPT-J-6B,v4,469,462,0.985075,0.014925
9,GPT-J-6B_v5,GPT-J-6B,v5,781,600,0.768246,0.231754

In [81]:
# https://stackoverflow.com/questions/50649853/trying-to-merge-2-dataframes-but-get-valueerror
# It gives error because it's using index of bleu df

df_decoding_joined = df_decoding_bleu4_th05.merge(df_decoding_criteria, on = "model_decoding_version",
                           suffixes = (None, "_y"))
df_decoding_joined.head()

,model_decoding_version,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,model_y,decoding_version_y,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B_v1,GPT-J-6B,v1,867,659,0.760092,0.239908,GPT-J-6B,v1,1,0,29,629,0.954476
1,GPT-J-6B_v2,GPT-J-6B,v2,439,424,0.965831,0.034169,GPT-J-6B,v2,2,1,4,417,0.983491
2,GPT-J-6B_v3,GPT-J-6B,v3,349,339,0.971347,0.028653,GPT-J-6B,v3,1,0,16,322,0.949853
3,GPT-J-6B_v4,GPT-J-6B,v4,469,462,0.985075,0.014925,GPT-J-6B,v4,2,0,7,453,0.980519
4,GPT-J-6B_v5,GPT-J-6B,v5,781,600,0.768246,0.231754,GPT-J-6B,v5,1,0,35,564,0.940000

In [82]:
df_decoding_joined = df_decoding_joined.drop(columns = ["model_decoding_version", "model_y" , "decoding_version_y"])
df_decoding_joined.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,867,659,0.760092,0.239908,1,0,29,629,0.954476
1,GPT-J-6B,v2,439,424,0.965831,0.034169,2,1,4,417,0.983491
2,GPT-J-6B,v3,349,339,0.971347,0.028653,1,0,16,322,0.949853
3,GPT-J-6B,v4,469,462,0.985075,0.014925,2,0,7,453,0.980519
4,GPT-J-6B,v5,781,600,0.768246,0.231754,1,0,35,564,0.940000

In [83]:
df_decoding_joined.insert(9, "Criteria_n_discarded", df_decoding_joined["BLEU4_remaining"] - df_decoding_joined["Criteria_n_remaining"])

In [84]:
df_decoding_joined.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining2
0,GPT-J-6B,v1,867,659,0.760092,0.239908,1,0,29,30,629,0.954476
1,GPT-J-6B,v2,439,424,0.965831,0.034169,2,1,4,7,417,0.983491
2,GPT-J-6B,v3,349,339,0.971347,0.028653,1,0,16,17,322,0.949853
3,GPT-J-6B,v4,469,462,0.985075,0.014925,2,0,7,9,453,0.980519
4,GPT-J-6B,v5,781,600,0.768246,0.231754,1,0,35,36,564,0.940000

In [85]:
df_decoding_joined.insert(12, r"Criteria_%discarded", df_decoding_joined["Criteria_n_discarded"]/df_decoding_joined["n_total"])

In [86]:
df_decoding_joined.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining2,Criteria_%discarded
0,GPT-J-6B,v1,867,659,0.760092,0.239908,1,0,29,30,629,0.954476,0.034602
1,GPT-J-6B,v2,439,424,0.965831,0.034169,2,1,4,7,417,0.983491,0.015945
2,GPT-J-6B,v3,349,339,0.971347,0.028653,1,0,16,17,322,0.949853,0.048711
3,GPT-J-6B,v4,469,462,0.985075,0.014925,2,0,7,9,453,0.980519,0.019190
4,GPT-J-6B,v5,781,600,0.768246,0.231754,1,0,35,36,564,0.940000,0.046095

In [87]:
df_decoding_joined.insert(11, r"Criteria_%remaining", df_decoding_joined["Criteria_n_remaining"]/df_decoding_joined["n_total"])

In [88]:
df_decoding_joined.head()

,model,decoding_version,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
0,GPT-J-6B,v1,867,659,0.760092,0.239908,1,0,29,30,629,0.725490,0.954476,0.034602
1,GPT-J-6B,v2,439,424,0.965831,0.034169,2,1,4,7,417,0.949886,0.983491,0.015945
2,GPT-J-6B,v3,349,339,0.971347,0.028653,1,0,16,17,322,0.922636,0.949853,0.048711
3,GPT-J-6B,v4,469,462,0.985075,0.014925,2,0,7,9,453,0.965885,0.980519,0.019190
4,GPT-J-6B,v5,781,600,0.768246,0.231754,1,0,35,36,564,0.722151,0.940000,0.046095

In [89]:
df_decoding_joined_mean = df_decoding_joined.groupby(["decoding_version"]).mean()
df_decoding_joined_mean

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
decoding_version,,,,,,,,,,,,
v1,711.2,544.2,0.761604,0.238396,1.0,0.0,28.4,29.4,514.8,0.723222,0.949542,0.038382
v2,346.8,332.0,0.953706,0.046294,0.8,0.2,5.6,6.6,325.4,0.935753,0.981320,0.017953
v3,285.0,270.4,0.944568,0.055432,0.6,0.0,4.4,5.0,265.4,0.929540,0.984467,0.015027
v4,374.2,359.4,0.957056,0.042944,0.6,0.0,6.4,7.0,352.4,0.938337,0.980439,0.018719
v5,664.4,545.0,0.816552,0.183448,2.6,0.0,31.0,33.6,511.4,0.770367,0.944023,0.046184
v6,336.0,318.6,0.943355,0.056645,1.0,0.2,3.6,4.8,313.8,0.928964,0.984738,0.014391
v7,362.4,347.0,0.948638,0.051362,1.2,1.0,9.8,12.0,335.0,0.916847,0.966543,0.031791
v8,666.2,523.8,0.765983,0.234017,1.0,0.2,26.2,27.4,496.4,0.730091,0.954774,0.035892

In [90]:
df_decoding_joined.groupby(["decoding_version"]).count()

,model,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
decoding_version,,,,,,,,,,,,,
v1,5,5,5,5,5,5,5,5,5,5,5,5,5
v2,5,5,5,5,5,5,5,5,5,5,5,5,5
v3,5,5,5,5,5,5,5,5,5,5,5,5,5
v4,5,5,5,5,5,5,5,5,5,5,5,5,5
v5,5,5,5,5,5,5,5,5,5,5,5,5,5
v6,5,5,5,5,5,5,5,5,5,5,5,5,5
v7,5,5,5,5,5,5,5,5,5,5,5,5,5
v8,5,5,5,5,5,5,5,5,5,5,5,5,5

In [91]:
df_decoding_joined_mean.to_csv("/home/pcallec/smoking_cessation_messages/results/vC/stats_filters/decoding_filters_joined_mean.csv")

In [92]:
df_decoding_joined.groupby(["decoding_version"]).count()["model"]

decoding_version
v1    5
v2    5
v3    5
v4    5
v5    5
v6    5
v7    5
v8    5
Name: model, dtype: int64

In [93]:
df_decoding_joined_stddev = df_decoding_joined.groupby(["decoding_version"]).std()
df_decoding_joined_stddev

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
decoding_version,,,,,,,,,,,,
v1,170.315002,140.538963,0.035858,0.035858,1.000000,0.000000,19.932386,19.743353,129.787133,0.044053,0.034640,0.025720
v2,86.742147,88.388348,0.022598,0.022598,1.095445,0.447214,3.435113,3.847077,85.488596,0.016038,0.009780,0.009648
v3,52.810984,57.334981,0.029135,0.029135,0.894427,0.000000,6.693280,7.000000,51.679783,0.019665,0.020539,0.019957
v4,72.764689,77.664664,0.022956,0.022956,0.894427,0.000000,1.341641,1.581139,76.346578,0.022758,0.002521,0.002436
v5,167.667230,146.720823,0.051043,0.051043,3.209361,0.000000,20.124612,20.959485,130.143382,0.046526,0.033463,0.027824
v6,69.411815,73.968236,0.030402,0.030402,1.224745,0.447214,2.408319,2.588436,73.411171,0.030934,0.006969,0.006687
v7,101.903386,107.226396,0.042561,0.042561,1.643168,2.236068,6.760178,9.565563,103.157646,0.046087,0.023780,0.022785
v8,229.577220,211.123660,0.075963,0.075963,1.732051,0.447214,17.340704,17.126004,194.428136,0.058690,0.023263,0.019283

In [94]:
df_decoding_joined_stddev.to_csv("/home/pcallec/smoking_cessation_messages/results/vC/stats_filters/decoding_filters_joined_stddev.csv")

In [95]:
df_decoding_joined_stderr = df_decoding_joined.groupby(["decoding_version"]).std()/5**0.5
df_decoding_joined_stderr

,n_total,BLEU4_remaining,BLEU4_%remaining,BLEU4_%discarded,Criteria_n_app,Criteria_n_underscore,Criteria_n_less_than_six_words,Criteria_n_discarded,Criteria_n_remaining,Criteria_%remaining,Criteria_%remaining2,Criteria_%discarded
decoding_version,,,,,,,,,,,,
v1,76.167185,62.850935,0.016036,0.016036,0.447214,0.0,8.914034,8.829496,58.042571,0.019701,0.015491,0.011502
v2,38.792267,39.528471,0.010106,0.010106,0.489898,0.2,1.536229,1.720465,38.231662,0.007172,0.004374,0.004315
v3,23.617790,25.640983,0.013030,0.013030,0.400000,0.0,2.993326,3.130495,23.111902,0.008794,0.009185,0.008925
v4,32.541358,34.732694,0.010266,0.010266,0.400000,0.0,0.600000,0.707107,34.143228,0.010178,0.001127,0.001089
v5,74.983065,65.615547,0.022827,0.022827,1.435270,0.0,9.000000,9.373367,58.201890,0.020807,0.014965,0.012443
v6,31.041907,33.079601,0.013596,0.013596,0.547723,0.2,1.077033,1.157584,32.830474,0.013834,0.003117,0.002991
v7,45.572579,47.953102,0.019034,0.019034,0.734847,1.0,3.023243,4.277850,46.133502,0.020611,0.010635,0.010190
v8,102.670054,94.417371,0.033972,0.033972,0.774597,0.2,7.754998,7.658982,86.950906,0.026247,0.010404,0.008624

In [96]:
df_decoding_joined_stderr.to_csv("/home/pcallec/smoking_cessation_messages/results/vC/stats_filters/decoding_filters_joined_stderr.csv")

# temp

In [97]:
df_stats = pd.read_csv('/home/pcallec/smoking_cessation_messages/results/vB/v2/statistics_discard_and_bleu.csv',
            header = [0], index_col = 0) 

df_stats.head()

,prompt version,model,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
1,v1,gpt-j-6B,878,685,0.78,0,0,42,643,0.73,0.94
2,v2,gpt-j-6B,925,675,0.73,0,0,33,642,0.69,0.95
3,v3,gpt-j-6B,930,712,0.77,0,0,31,681,0.73,0.96
4,v4,gpt-j-6B,1523,402,0.26,0,29,138,263,0.17,0.65
5,v5,gpt-j-6B,772,562,0.73,2,0,31,529,0.69,0.94

In [101]:
df_stats.columns

Index(['prompt version', 'model', 'BLEU-# messages', 'BLEU-# remaining',
       'BLEU-% remaining', 'BLEU-n_app', 'BLEU-n_underscore',
       'BLEU-n_less_than_six_words', 'Criteria-# remaining',
       'Criteria-% remaining1', 'Criteria-% remaining2'],
      dtype='object')

## means

In [102]:
df_stats_mean = df_stats.groupby('prompt version').mean()
df_stats_mean

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
prompt version,,,,,,,,,
v1,739.2,545.0,0.730,0.8,0.0,29.8,514.4,0.690,0.950
v2,754.2,576.8,0.766,1.8,0.0,24.8,550.4,0.732,0.956
v3,803.4,598.0,0.752,0.8,0.0,26.8,570.4,0.716,0.956
v4,1376.0,365.6,0.272,1.2,6.4,100.8,262.8,0.202,0.732
v5,673.0,454.2,0.668,0.8,0.0,21.6,431.8,0.638,0.954

In [103]:
l_columns = df_stats_mean.columns

In [104]:
l_columns[0]

'BLEU-# messages'

In [105]:
l_new_column_names = []
d_change_col_names = dict()
for i_column in l_columns:
    new_column_name = i_column +  "-mean"
    l_new_column_names.append(new_column_name)
    d_change_col_names[i_column] = new_column_name

In [106]:
l_new_column_names

['BLEU-# messages-mean',
 'BLEU-# remaining-mean',
 'BLEU-% remaining-mean',
 'BLEU-n_app-mean',
 'BLEU-n_underscore-mean',
 'BLEU-n_less_than_six_words-mean',
 'Criteria-# remaining-mean',
 'Criteria-% remaining1-mean',
 'Criteria-% remaining2-mean']

In [107]:
d_change_col_names

{'BLEU-# messages': 'BLEU-# messages-mean',
 'BLEU-# remaining': 'BLEU-# remaining-mean',
 'BLEU-% remaining': 'BLEU-% remaining-mean',
 'BLEU-n_app': 'BLEU-n_app-mean',
 'BLEU-n_underscore': 'BLEU-n_underscore-mean',
 'BLEU-n_less_than_six_words': 'BLEU-n_less_than_six_words-mean',
 'Criteria-# remaining': 'Criteria-# remaining-mean',
 'Criteria-% remaining1': 'Criteria-% remaining1-mean',
 'Criteria-% remaining2': 'Criteria-% remaining2-mean'}

In [108]:
df_stats_mean.rename(columns = d_change_col_names, inplace=True)

In [109]:
df_stats_mean.columns

Index(['BLEU-# messages-mean', 'BLEU-# remaining-mean',
       'BLEU-% remaining-mean', 'BLEU-n_app-mean', 'BLEU-n_underscore-mean',
       'BLEU-n_less_than_six_words-mean', 'Criteria-# remaining-mean',
       'Criteria-% remaining1-mean', 'Criteria-% remaining2-mean'],
      dtype='object')

In [110]:
df_stats_mean

,BLEU-# messages-mean,BLEU-# remaining-mean,BLEU-% remaining-mean,BLEU-n_app-mean,BLEU-n_underscore-mean,BLEU-n_less_than_six_words-mean,Criteria-# remaining-mean,Criteria-% remaining1-mean,Criteria-% remaining2-mean
prompt version,,,,,,,,,
v1,739.2,545.0,0.730,0.8,0.0,29.8,514.4,0.690,0.950
v2,754.2,576.8,0.766,1.8,0.0,24.8,550.4,0.732,0.956
v3,803.4,598.0,0.752,0.8,0.0,26.8,570.4,0.716,0.956
v4,1376.0,365.6,0.272,1.2,6.4,100.8,262.8,0.202,0.732
v5,673.0,454.2,0.668,0.8,0.0,21.6,431.8,0.638,0.954

## std error

In [111]:
df_stats_std = df_stats.groupby('prompt version').std(ddof = 1)
df_stats_std

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
prompt version,,,,,,,,,
v1,165.341162,147.778551,0.054772,0.836660,0.000000,16.452963,133.932072,0.046904,0.025495
v2,197.227534,152.470325,0.058992,2.167948,0.000000,18.700267,143.780388,0.069785,0.023022
v3,207.571193,155.183762,0.075299,1.303840,0.000000,13.179530,144.937228,0.084735,0.023022
v4,353.307232,70.251690,0.035637,1.095445,12.660964,45.920584,29.003448,0.056745,0.102567
v5,86.717934,86.082519,0.047645,0.836660,0.000000,15.290520,75.945375,0.034205,0.032863

In [112]:
# 5 because of 5 models: gptj6b, bloom, opt6.7b, opt13b, opt30b
df_stats_std_err = df_stats_std/5**0.5

In [113]:
df_stats_std_err

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
prompt version,,,,,,,,,
v1,73.942816,66.088577,0.024495,0.374166,0.000000,7.357989,59.896244,0.020976,0.011402
v2,88.202834,68.186802,0.026382,0.969536,0.000000,8.363014,64.300544,0.031209,0.010296
v3,92.828659,69.400288,0.033675,0.583095,0.000000,5.894065,64.817899,0.037895,0.010296
v4,158.003797,31.417511,0.015937,0.489898,5.662155,20.536309,12.970736,0.025377,0.045869
v5,38.781439,38.497273,0.021307,0.374166,0.000000,6.838128,33.963804,0.015297,0.014697

In [114]:
l_columns = df_stats_std_err.columns

In [115]:
l_new_column_names = []
d_change_col_names = dict()
for i_column in l_columns:
    new_column_name = i_column +  "-err"
    l_new_column_names.append(new_column_name)
    d_change_col_names[i_column] = new_column_name

In [116]:
df_stats_std_err.rename(columns = d_change_col_names, inplace=True)

In [117]:
df_stats_std_err

,BLEU-# messages-err,BLEU-# remaining-err,BLEU-% remaining-err,BLEU-n_app-err,BLEU-n_underscore-err,BLEU-n_less_than_six_words-err,Criteria-# remaining-err,Criteria-% remaining1-err,Criteria-% remaining2-err
prompt version,,,,,,,,,
v1,73.942816,66.088577,0.024495,0.374166,0.000000,7.357989,59.896244,0.020976,0.011402
v2,88.202834,68.186802,0.026382,0.969536,0.000000,8.363014,64.300544,0.031209,0.010296
v3,92.828659,69.400288,0.033675,0.583095,0.000000,5.894065,64.817899,0.037895,0.010296
v4,158.003797,31.417511,0.015937,0.489898,5.662155,20.536309,12.970736,0.025377,0.045869
v5,38.781439,38.497273,0.021307,0.374166,0.000000,6.838128,33.963804,0.015297,0.014697

In [118]:
df_stats_mean_std_err = df_stats_mean.join(df_stats_std_err)
df_stats_mean_std_err

,BLEU-# messages-mean,BLEU-# remaining-mean,BLEU-% remaining-mean,BLEU-n_app-mean,BLEU-n_underscore-mean,BLEU-n_less_than_six_words-mean,Criteria-# remaining-mean,Criteria-% remaining1-mean,Criteria-% remaining2-mean,BLEU-# messages-err,BLEU-# remaining-err,BLEU-% remaining-err,BLEU-n_app-err,BLEU-n_underscore-err,BLEU-n_less_than_six_words-err,Criteria-# remaining-err,Criteria-% remaining1-err,Criteria-% remaining2-err
prompt version,,,,,,,,,,,,,,,,,,
v1,739.2,545.0,0.730,0.8,0.0,29.8,514.4,0.690,0.950,73.942816,66.088577,0.024495,0.374166,0.000000,7.357989,59.896244,0.020976,0.011402
v2,754.2,576.8,0.766,1.8,0.0,24.8,550.4,0.732,0.956,88.202834,68.186802,0.026382,0.969536,0.000000,8.363014,64.300544,0.031209,0.010296
v3,803.4,598.0,0.752,0.8,0.0,26.8,570.4,0.716,0.956,92.828659,69.400288,0.033675,0.583095,0.000000,5.894065,64.817899,0.037895,0.010296
v4,1376.0,365.6,0.272,1.2,6.4,100.8,262.8,0.202,0.732,158.003797,31.417511,0.015937,0.489898,5.662155,20.536309,12.970736,0.025377,0.045869
v5,673.0,454.2,0.668,0.8,0.0,21.6,431.8,0.638,0.954,38.781439,38.497273,0.021307,0.374166,0.000000,6.838128,33.963804,0.015297,0.014697

In [119]:
l_col_mean_std_err = df_stats_mean_std_err.columns
l_col_mean_std_err_ordered = []

n_real_columns = int(len(l_col_mean_std_err)/2)

for i in range(n_real_columns):
    l_col_mean_std_err_ordered.extend([l_col_mean_std_err[i],l_col_mean_std_err[n_real_columns+i]])

In [120]:
df_stats_mean_std_err = df_stats_mean_std_err[l_col_mean_std_err_ordered]

In [121]:
df_stats_mean_std_err.to_csv("/home/pcallec/smoking_cessation_messages/results/vB/v2/stats_filters/stats_filters_vB_v2.csv")

# Read file vC

In [98]:
df_stats = pd.read_csv('/home/pcallec/smoking_cessation_messages/results/vC/statistics_discard_and_bleu.csv',
            header = [0], index_col = 0) 

df_stats.head()

,model,decoding version,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
1,gpt-j-6B,v1,867,659,0.76,1,0,29,629,0.73,0.95
2,gpt-j-6B,v2,439,424,0.97,2,1,4,417,0.95,0.98
3,gpt-j-6B,v3,349,339,0.97,1,0,16,322,0.92,0.95
4,gpt-j-6B,v4,469,462,0.99,2,0,7,453,0.97,0.98
5,gpt-j-6B,v5,781,600,0.77,1,0,35,564,0.72,0.94

In [123]:
df_stats.columns

Index(['model', 'decoding version', 'BLEU-# messages', 'BLEU-# remaining',
       'BLEU-% remaining', 'BLEU-n_app', 'BLEU-n_underscore',
       'BLEU-n_less_than_six_words', 'Criteria-# remaining',
       'Criteria-% remaining1', 'Criteria-% remaining2'],
      dtype='object')

In [124]:
def get_decoding_version(str_type):
    model = None
    decoding_version = None
    
    if str_type != "original":
        items = str_type.split('_')
        
        model = items[0]
        decoding_version = items[4]
        
    else:
        decoding_version = "human"
        
    return decoding_version

## means

In [125]:
df_stats_mean = df_stats.groupby('decoding version').mean()
df_stats_mean

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
decoding version,,,,,,,,,
v1,711.2,544.2,0.762,1.0,0.0,28.4,514.8,0.724,0.948
v2,346.8,332.0,0.956,0.8,0.2,5.6,325.4,0.934,0.982
v3,285.0,270.4,0.944,0.6,0.0,4.4,265.4,0.930,0.986
v4,374.2,359.4,0.958,0.6,0.0,6.4,352.4,0.938,0.980
v5,664.4,545.0,0.816,2.6,0.0,31.0,511.4,0.772,0.944
v6,336.0,318.6,0.944,1.0,0.2,3.6,313.8,0.930,0.986
v7,362.4,347.0,0.950,1.2,1.0,9.8,335.0,0.916,0.968
v8,666.2,523.8,0.766,1.0,0.2,26.2,496.4,0.730,0.954

In [126]:
l_columns = df_stats_mean.columns

In [127]:
l_columns[0]

'BLEU-# messages'

In [128]:
l_new_column_names = []
d_change_col_names = dict()
for i_column in l_columns:
    new_column_name = i_column +  "-mean"
    l_new_column_names.append(new_column_name)
    d_change_col_names[i_column] = new_column_name

In [129]:
l_new_column_names

['BLEU-# messages-mean',
 'BLEU-# remaining-mean',
 'BLEU-% remaining-mean',
 'BLEU-n_app-mean',
 'BLEU-n_underscore-mean',
 'BLEU-n_less_than_six_words-mean',
 'Criteria-# remaining-mean',
 'Criteria-% remaining1-mean',
 'Criteria-% remaining2-mean']

In [130]:
d_change_col_names

{'BLEU-# messages': 'BLEU-# messages-mean',
 'BLEU-# remaining': 'BLEU-# remaining-mean',
 'BLEU-% remaining': 'BLEU-% remaining-mean',
 'BLEU-n_app': 'BLEU-n_app-mean',
 'BLEU-n_underscore': 'BLEU-n_underscore-mean',
 'BLEU-n_less_than_six_words': 'BLEU-n_less_than_six_words-mean',
 'Criteria-# remaining': 'Criteria-# remaining-mean',
 'Criteria-% remaining1': 'Criteria-% remaining1-mean',
 'Criteria-% remaining2': 'Criteria-% remaining2-mean'}

In [131]:
df_stats_mean.rename(columns = d_change_col_names, inplace=True)

In [132]:
df_stats_mean.columns

Index(['BLEU-# messages-mean', 'BLEU-# remaining-mean',
       'BLEU-% remaining-mean', 'BLEU-n_app-mean', 'BLEU-n_underscore-mean',
       'BLEU-n_less_than_six_words-mean', 'Criteria-# remaining-mean',
       'Criteria-% remaining1-mean', 'Criteria-% remaining2-mean'],
      dtype='object')

In [133]:
df_stats_mean

,BLEU-# messages-mean,BLEU-# remaining-mean,BLEU-% remaining-mean,BLEU-n_app-mean,BLEU-n_underscore-mean,BLEU-n_less_than_six_words-mean,Criteria-# remaining-mean,Criteria-% remaining1-mean,Criteria-% remaining2-mean
decoding version,,,,,,,,,
v1,711.2,544.2,0.762,1.0,0.0,28.4,514.8,0.724,0.948
v2,346.8,332.0,0.956,0.8,0.2,5.6,325.4,0.934,0.982
v3,285.0,270.4,0.944,0.6,0.0,4.4,265.4,0.930,0.986
v4,374.2,359.4,0.958,0.6,0.0,6.4,352.4,0.938,0.980
v5,664.4,545.0,0.816,2.6,0.0,31.0,511.4,0.772,0.944
v6,336.0,318.6,0.944,1.0,0.2,3.6,313.8,0.930,0.986
v7,362.4,347.0,0.950,1.2,1.0,9.8,335.0,0.916,0.968
v8,666.2,523.8,0.766,1.0,0.2,26.2,496.4,0.730,0.954

## std error

In [134]:
df_stats_std = df_stats.groupby('decoding version').std(ddof = 1)
df_stats_std

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
decoding version,,,,,,,,,
v1,170.315002,140.538963,0.034205,1.000000,0.000000,19.932386,129.787133,0.046152,0.033466
v2,86.742147,88.388348,0.024083,1.095445,0.447214,3.435113,85.488596,0.018166,0.010954
v3,52.810984,57.334981,0.028810,0.894427,0.000000,6.693280,51.679783,0.021213,0.020736
v4,72.764689,77.664664,0.024900,0.894427,0.000000,1.341641,76.346578,0.025884,0.000000
v5,167.667230,146.720823,0.049800,3.209361,0.000000,20.124612,130.143382,0.048166,0.032094
v6,69.411815,73.968236,0.032863,1.224745,0.447214,2.408319,73.411171,0.030822,0.005477
v7,101.903386,107.226396,0.041231,1.643168,2.236068,6.760178,103.157646,0.043359,0.021679
v8,229.577220,211.123660,0.074364,1.732051,0.447214,17.340704,194.428136,0.060415,0.020736

In [135]:
# 5 because of 5 models: gptj6b, bloom, opt6.7b, opt13b, opt30b
df_stats_std_err = df_stats_std/5**0.5

In [136]:
df_stats_std_err

,BLEU-# messages,BLEU-# remaining,BLEU-% remaining,BLEU-n_app,BLEU-n_underscore,BLEU-n_less_than_six_words,Criteria-# remaining,Criteria-% remaining1,Criteria-% remaining2
decoding version,,,,,,,,,
v1,76.167185,62.850935,0.015297,0.447214,0.0,8.914034,58.042571,0.020640,0.014967
v2,38.792267,39.528471,0.010770,0.489898,0.2,1.536229,38.231662,0.008124,0.004899
v3,23.617790,25.640983,0.012884,0.400000,0.0,2.993326,23.111902,0.009487,0.009274
v4,32.541358,34.732694,0.011136,0.400000,0.0,0.600000,34.143228,0.011576,0.000000
v5,74.983065,65.615547,0.022271,1.435270,0.0,9.000000,58.201890,0.021541,0.014353
v6,31.041907,33.079601,0.014697,0.547723,0.2,1.077033,32.830474,0.013784,0.002449
v7,45.572579,47.953102,0.018439,0.734847,1.0,3.023243,46.133502,0.019391,0.009695
v8,102.670054,94.417371,0.033257,0.774597,0.2,7.754998,86.950906,0.027019,0.009274

In [137]:
l_columns = df_stats_std_err.columns

In [138]:
l_new_column_names = []
d_change_col_names = dict()
for i_column in l_columns:
    new_column_name = i_column +  "-err"
    l_new_column_names.append(new_column_name)
    d_change_col_names[i_column] = new_column_name

In [139]:
df_stats_std_err.rename(columns = d_change_col_names, inplace=True)

In [140]:
df_stats_std_err

,BLEU-# messages-err,BLEU-# remaining-err,BLEU-% remaining-err,BLEU-n_app-err,BLEU-n_underscore-err,BLEU-n_less_than_six_words-err,Criteria-# remaining-err,Criteria-% remaining1-err,Criteria-% remaining2-err
decoding version,,,,,,,,,
v1,76.167185,62.850935,0.015297,0.447214,0.0,8.914034,58.042571,0.020640,0.014967
v2,38.792267,39.528471,0.010770,0.489898,0.2,1.536229,38.231662,0.008124,0.004899
v3,23.617790,25.640983,0.012884,0.400000,0.0,2.993326,23.111902,0.009487,0.009274
v4,32.541358,34.732694,0.011136,0.400000,0.0,0.600000,34.143228,0.011576,0.000000
v5,74.983065,65.615547,0.022271,1.435270,0.0,9.000000,58.201890,0.021541,0.014353
v6,31.041907,33.079601,0.014697,0.547723,0.2,1.077033,32.830474,0.013784,0.002449
v7,45.572579,47.953102,0.018439,0.734847,1.0,3.023243,46.133502,0.019391,0.009695
v8,102.670054,94.417371,0.033257,0.774597,0.2,7.754998,86.950906,0.027019,0.009274

In [141]:
df_stats_mean_std_err = df_stats_mean.join(df_stats_std_err)
df_stats_mean_std_err

,BLEU-# messages-mean,BLEU-# remaining-mean,BLEU-% remaining-mean,BLEU-n_app-mean,BLEU-n_underscore-mean,BLEU-n_less_than_six_words-mean,Criteria-# remaining-mean,Criteria-% remaining1-mean,Criteria-% remaining2-mean,BLEU-# messages-err,BLEU-# remaining-err,BLEU-% remaining-err,BLEU-n_app-err,BLEU-n_underscore-err,BLEU-n_less_than_six_words-err,Criteria-# remaining-err,Criteria-% remaining1-err,Criteria-% remaining2-err
decoding version,,,,,,,,,,,,,,,,,,
v1,711.2,544.2,0.762,1.0,0.0,28.4,514.8,0.724,0.948,76.167185,62.850935,0.015297,0.447214,0.0,8.914034,58.042571,0.020640,0.014967
v2,346.8,332.0,0.956,0.8,0.2,5.6,325.4,0.934,0.982,38.792267,39.528471,0.010770,0.489898,0.2,1.536229,38.231662,0.008124,0.004899
v3,285.0,270.4,0.944,0.6,0.0,4.4,265.4,0.930,0.986,23.617790,25.640983,0.012884,0.400000,0.0,2.993326,23.111902,0.009487,0.009274
v4,374.2,359.4,0.958,0.6,0.0,6.4,352.4,0.938,0.980,32.541358,34.732694,0.011136,0.400000,0.0,0.600000,34.143228,0.011576,0.000000
v5,664.4,545.0,0.816,2.6,0.0,31.0,511.4,0.772,0.944,74.983065,65.615547,0.022271,1.435270,0.0,9.000000,58.201890,0.021541,0.014353
v6,336.0,318.6,0.944,1.0,0.2,3.6,313.8,0.930,0.986,31.041907,33.079601,0.014697,0.547723,0.2,1.077033,32.830474,0.013784,0.002449
v7,362.4,347.0,0.950,1.2,1.0,9.8,335.0,0.916,0.968,45.572579,47.953102,0.018439,0.734847,1.0,3.023243,46.133502,0.019391,0.009695
v8,666.2,523.8,0.766,1.0,0.2,26.2,496.4,0.730,0.954,102.670054,94.417371,0.033257,0.774597,0.2,7.754998,86.950906,0.027019,0.009274

In [142]:
l_col_mean_std_err = df_stats_mean_std_err.columns
l_col_mean_std_err_ordered = []

n_real_columns = int(len(l_col_mean_std_err)/2)

for i in range(n_real_columns):
    l_col_mean_std_err_ordered.extend([l_col_mean_std_err[i],l_col_mean_std_err[n_real_columns+i]])

In [143]:
df_stats_mean_std_err = df_stats_mean_std_err[l_col_mean_std_err_ordered]

In [144]:
df_stats_mean_std_err.to_csv("/home/pcallec/smoking_cessation_messages/results/vC/stats_filters/stats_filters_vC.csv")